;/*FB_PKG_DELIM*/

__d("CometPrimaryProfilePlusOnboardingFalcoEvent",["FalcoLoggerInternal","getFalcoLogPolicy_DO_NOT_USE"],(function(a,b,c,d,e,f,g){"use strict";a=c("getFalcoLogPolicy_DO_NOT_USE")("3190");b=d("FalcoLoggerInternal").create("comet_primary_profile_plus_onboarding",a);e=b;g["default"]=e}),98);
__d("CometTextColorEntityRenderer_entity.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:{mask:!1},name:"CometTextColorEntityRenderer_entity",selections:[{alias:null,args:null,kind:"ScalarField",name:"hex_rgb_color_with_pound_key",storageKey:null}],type:"ColorAtRange",abstractKey:null};e.exports=a}),null);
__d("CometTextColorEntityRenderer",["CometTextColorEntityRenderer_entity.graphql","react","react-strict-dom"],(function(a,b,c,d,e,f,g){"use strict";var h,i,j=i||d("react"),k={color:function(a){return[{color:a!=null?"x14rh7hd":a,$$css:!0},{"--x-color":a!=null?a:void 0}]}};h!==void 0?h:h=b("CometTextColorEntityRenderer_entity.graphql");a=function(a,b){b=b.hex_rgb_color_with_pound_key;return b==null?a:j.jsx(d("react-strict-dom").html.span,{style:k.color(b),children:a})};g["default"]=a}),98);
__d("FbNotesEventsWebLogger",["requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h=c("requireDeferred")("FbNotesEventsFalcoEvent").__setRef("FbNotesEventsWebLogger"),i="2220391788200892";function a(a){var b=a.action,c=a.audioClusterId,d=a.creationSessionId,e=a.entrypoint,f=a.errorCode,g=a.errorMessage,j=a.extras,k=a.hasText,l=a.noteContentTypes,m=a.noteId,n=a.noteOriginAppId,o=n===void 0?i:n,p=a.noteType,q=a.noteVisibility,r=a.textLength;h.onReady(function(a){var h={action:b,audio_cluster_id:c,creation_session_id:d,entrypoint:e,error_code:f,error_message:g,extras:j,has_text:k,note_content_types:l,note_id:m,note_origin_app_id:o,note_type:p,note_visibility:q,text_length:r};a.log(function(){return h})})}g.logFbNotesEvent=a}),98);
__d("MWInboxTrayNoteCreationDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="30899655739648624"}),null);
__d("MWInboxTrayNoteCreationDialogQuery$Parameters",["MWInboxTrayNoteCreationDialogQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a={kind:"PreloadableConcreteRequest",params:{id:b("MWInboxTrayNoteCreationDialogQuery_facebookRelayOperation"),metadata:{},name:"MWInboxTrayNoteCreationDialogQuery",operationKind:"query",text:null}};e.exports=a}),null);
__d("MWInboxTrayNoteCreationDialog.entrypoint",["JSResourceForInteraction","MWInboxTrayNoteCreationDialogQuery$Parameters","WebPixelRatio"],(function(a,b,c,d,e,f,g){"use strict";a={getPreloadProps:function(){return{queries:{MWInboxTrayNoteCreationDialogQueryRef:{options:{fetchPolicy:"network-only"},parameters:c("MWInboxTrayNoteCreationDialogQuery$Parameters"),variables:{scale:d("WebPixelRatio").get()}}}}},root:c("JSResourceForInteraction")("MWInboxTrayNoteCreationDialog.react").__setRef("MWInboxTrayNoteCreationDialog.entrypoint")};g["default"]=a}),98);
__d("ProfileCometEntityConvergenceHeaderTopRow_renderer$normalization.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"SplitOperation",metadata:{},name:"ProfileCometEntityConvergenceHeaderTopRow_renderer$normalization",selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}]};e.exports=a}),null);
__d("ProfileCometManageSectionsDialogQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="9353838248046898"}),null);
__d("XCometAvatarEditorControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/avatar/edit/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("partitionArray",[],(function(a,b,c,d,e,f){function a(a,b,c){var d=[],e=[];a.forEach(function(f,g){b.call(c,f,g,a)?d.push(f):e.push(f)});return[d,e]}f["default"]=a}),66);
__d("useFxGrowthIdentitySyncingFalcoEventLogger",["Actor","FXUtils","promiseDone","react","requireDeferred"],(function(a,b,c,d,e,f,g){"use strict";var h,i=(h||d("react")).useCallback,j=c("requireDeferred")("FxGrowthIdentitySyncingFalcoEvent").__setRef("useFxGrowthIdentitySyncingFalcoEventLogger");function a(){var a=d("Actor").useActor(),b=a[0];return i(function(a){c("promiseDone")(j.load(),function(c){c.log(function(){return babelHelpers["extends"]({},a,{initiator_account_id:b,initiator_account_type:d("FXUtils").getFXClientActorAccountType()})})})},[b])}g["default"]=a}),98);
__d("useMaybeNUX_nux.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useMaybeNUX_nux",selections:[{alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"nux_id",storageKey:null},{alias:null,args:null,kind:"ScalarField",name:"should_show",storageKey:null}],type:"DefaultNUX",abstractKey:null};e.exports=a}),null);
__d("useMaybeNUX",["CometRelay","emptyFunction","react","react-compiler-runtime","useMaybeNUX_nux.graphql","useNUX"],(function(a,b,c,d,e,f,g){"use strict";var h,i;e=i||d("react");e.useCallback;var j=e.useEffect;function a(a){var e=d("react-compiler-runtime").c(13),f=d("CometRelay").useRelayEnvironment();a=d("CometRelay").useFragment(h!==void 0?h:h=b("useMaybeNUX_nux.graphql"),a);var g=a==null?void 0:a.id,i=a==null?void 0:a.nux_id,k=c("useNUX")(i,Boolean(a==null?void 0:a.should_show)),l=k[0],m=k[1],n=l&&(a==null?void 0:a.should_show)===!0&&i!=null;e[0]!==f||e[1]!==m||e[2]!==g?(k=function(){m==null||m.onDismiss();if(g==null)return;d("CometRelay").commitLocalUpdate(f,function(a){a=a.get(g);a==null||a.setValue(!1,"should_show")})},e[0]=f,e[1]=m,e[2]=g,e[3]=k):k=e[3];l=k;var o;e[4]!==n||e[5]!==m||e[6]!==i?(k=function(){i!=null&&n&&(m==null||m.onVisible())},o=[i,n,m],e[4]=n,e[5]=m,e[6]=i,e[7]=k,e[8]=o):(k=e[7],o=e[8]);j(k,o);e[9]!==l||e[10]!==n||e[11]!==a?(k=a!=null?[n,l]:[null,c("emptyFunction")],e[9]=l,e[10]=n,e[11]=a,e[12]=k):k=e[12];return k}g["default"]=a}),98);
__d("useProfileCometStoryStatus_user.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null};return{argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useProfileCometStoryStatus_user",selections:[{alias:null,args:[{kind:"Literal",name:"first",value:1}],concreteType:"DirectInboxBroadcastBucketConnection",kind:"LinkedField",name:"story_bucket",plural:!1,selections:[{alias:null,args:null,concreteType:"DirectMessageThreadBucket",kind:"LinkedField",name:"nodes",plural:!0,selections:[{alias:null,args:null,kind:"ScalarField",name:"should_show_close_friend_badge",storageKey:null},a,{alias:null,args:null,concreteType:"Story",kind:"LinkedField",name:"first_story_to_show",plural:!1,selections:[a,{alias:null,args:null,concreteType:"StoryCardSeenState",kind:"LinkedField",name:"story_card_seen_state",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"is_seen_by_viewer",storageKey:null}],storageKey:null},{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"story_overlays",plural:!0,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null}],storageKey:null}],storageKey:null}],storageKey:null}],storageKey:"story_bucket(first:1)"}],type:"User",abstractKey:null}}();e.exports=a}),null);
__d("useProfileCometStoryStatus",["CometRelay","StoriesEnums","XCometStoriesControllerRouteBuilder","getCometNotesGating","react","react-compiler-runtime","useProfileCometStoryStatus_user.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h,i;i||d("react");function a(a){var e=d("react-compiler-runtime").c(7);a=d("CometRelay").useFragment(h!==void 0?h:h=b("useProfileCometStoryStatus_user.graphql"),a);var f="none",g;a=(a=a.story_bucket)==null?void 0:a.nodes;var i=!1;if(a){var k;a=a?a[0]:null;var l=(a==null?void 0:a.id)||null,m=(a==null||(k=a.first_story_to_show)==null?void 0:k.id)||null;if(a&&l&&m){var n;n=((n=a.first_story_to_show)==null||(n=n.story_overlays)==null?void 0:n.some(j))===!0;if(n&&!d("getCometNotesGating").getIsNotesCreationDialogEnabled())f="none";else{n=((n=a.first_story_to_show)==null||(n=n.story_card_seen_state)==null?void 0:n.is_seen_by_viewer)||!1;f=n?"seen":"unseen";i=(n=a.should_show_close_friend_badge)!=null?n:!1}}if(f!=="none"){e[0]!==l||e[1]!==m?(a=c("XCometStoriesControllerRouteBuilder").buildURL({bucket_id:l,card_id:m,view_single:!1}),e[0]=l,e[1]=m,e[2]=a):a=e[2];g=a}}e[3]!==i||e[4]!==f||e[5]!==g?(n={shouldShowCloseFriendsBadge:i,storyStatus:f,storyUrl:g},e[3]=i,e[4]=f,e[5]=g,e[6]=n):n=e[6];return n}function j(a){return a.__typename===d("StoriesEnums").STORY_OVERLAY_TYPES.FB_NOTES_STICKER}g["default"]=a}),98);